# This is a Docker Compose file for setting up a PostgreSQL database service.
# This is just a utility file to help you get started quickly with PostgreSQL in a Docker environment
# when trying any code using this library.

services:
  postgres:
    image: postgres:17.5
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres_db}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-crablet}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-crablet}
      POSTGRES_DB: ${POSTGRES_DB:-crablet}
      # Authentication settings for benchmarks
      POSTGRES_HOST_AUTH_METHOD: trust
      # Suppress application-level exceptions from being logged
      POSTGRES_LOG_MIN_MESSAGES: "fatal"
      # Performance tuning for benchmarks
      POSTGRES_SHARED_BUFFERS: 2GB
      POSTGRES_WORK_MEM: 128MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 4GB
      POSTGRES_MAINTENANCE_WORK_MEM: 512MB
      POSTGRES_CHECKPOINT_COMPLETION_TARGET: 0.9
      POSTGRES_WAL_BUFFERS: 64MB
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    # Use environment variables for performance tuning instead of custom postgresql.conf
    # Resource allocation for better performance
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 6G
        reservations:
          cpus: '2.0'
          memory: 4G
    # Alternative resource limits for older Docker Compose versions
    mem_limit: 6g
    cpus: 4.0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: