# This is a Docker Compose file for setting up a PostgreSQL database service.
# This is just a utility file to help you get started quickly with PostgreSQL in a Docker environment
# when trying any code using this library.

services:
  postgres:
    image: postgres:16.10
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres_db}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-crablet}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-crablet}
      POSTGRES_DB: ${POSTGRES_DB:-crablet}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crablet"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: